import type { Metadata } from 'next'
import type React from 'react'
import '@/app/globals.css'
import { Footer } from '@/components/footer'
import { Header } from '@/components/header'
import PlausibleAnalytics from '@/components/tools/plausible'
import { TailwindIndicator } from '@/components/tools/tailwind-indicator'
import { DEFAULT_LOCALE, routing } from '@/i18n/routing'
import { cn } from '@/lib/utils'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'
import { ThemeProvider } from 'next-themes'
import { notFound } from 'next/navigation'
import { StrictMode } from 'react'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default async function RootLayout({
	children,
	params
}: Readonly<{
	children: React.ReactNode
	params: {
		locale: string
	}
}>) {
	const { locale } = await params

	// 确保传入的“语言环境”有效
	if (!routing.locales.includes(locale as any)) {
		notFound()
	}

	// 客户端提供所有翻译文件
	const messages = await getMessages()

	return (
		<StrictMode>
			<html lang={locale || DEFAULT_LOCALE} suppressHydrationWarning>
				<head />
				<body className={cn('min-h-screen bg-background flex flex-col antialiased')}>
					<NextIntlClientProvider messages={messages}>
						<ThemeProvider>
							<main className='max-w-7xl mx-auto flex flex-col items-center'>
								<Header />
								{children}
								<Footer />
							</main>
						</ThemeProvider>
					</NextIntlClientProvider>
					<TailwindIndicator />
					{process.env.NODE_ENV === 'production' && <PlausibleAnalytics />}
				</body>
			</html>
		</StrictMode>
	)
}
